core/urls.py
from django.urls import path

from core.views import main_page, portfolio_page, about_us_page, PortfolioDetailView, ContactUsView, VacanciesView

app_name = "core"

urlpatterns = [
    path('', main_page, name='home'),
    path('about', about_us_page, name='about us'),
    path('portfolio', portfolio_page, name='portfolio'),
    path('portfolio/<int:pk>', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('contacts', ContactUsView.as_view(), name='contacts'),
    path('vacancies', VacanciesView.as_view(), name='vacancies'),

]

itunisoft_hybrid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = "IT UniSoft Admin"
admin.site.site_title = "IT UniSoft Admin Portal"
admin.site.index_title = "Welcome to IT UniSoft Admin official web-site!"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'main_app')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('main/', include('core.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/models/about.py
from uuid import uuid4

from ckeditor.fields import RichTextField
from django.db import models


def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    file_path = 'about/{filename}'.format(
        filename='{}.{}'.format(uuid4().hex, ext)
    )
    return file_path


class AboutInfoModel(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    body = RichTextField(blank=True, null=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Biz haqimizda'
        verbose_name_plural = 'Biz haqimizda'


class CertificatesModel(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    img = models.ImageField(upload_to=upload_location, blank=True, null=True)

    @property
    def imageURL(self):
        try:
            url = str(self.img.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Sertifikatlar'
        verbose_name_plural = 'Sertifikatlar'


class VacancyModel(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    body = RichTextField(blank=True, null=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Vakansiyalar'
        verbose_name_plural = 'Vakansiyalar'

core/models/home.py
from uuid import uuid4

from ckeditor.fields import RichTextField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
import random as r


def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    file_path = 'home/{filename}'.format(
        filename='{}.{}'.format(uuid4().hex, ext)
    )
    return file_path


class PartnerCategoryModel(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Hamkorlar Kategoriyasi'
        verbose_name_plural = 'Hamkorlar Kategoriyasi'


class PartnersModel(models.Model):
    img = models.ImageField(upload_to=upload_location, blank=True, null=True)
    category = models.ForeignKey(PartnerCategoryModel, related_name='partners', on_delete=models.SET_NULL, null=True)

    @property
    def imageURL(self):
        try:
            url = str(self.img.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.category.name)

    class Meta:
        verbose_name = 'Hamkorlarimiz'
        verbose_name_plural = 'Hamkorlarimiz'


class CarouselModel(models.Model):
    img = models.ImageField(upload_to=upload_location, blank=True, null=True)
    title = models.TextField()

    @property
    def imageURL(self):
        try:
            url = str(self.img.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.title)




class StatsModel(models.Model):
    numbers = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=255)

    def __str__(self):
        return str(self.title)


class InfoPageModel(models.Model):
    image = models.ImageField(upload_to=upload_location, blank=True, null=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body = RichTextField()
    slug = models.SlugField(unique=True, blank=True)

    @property
    def imageURL(self):
        try:
            url = str(self.image.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.title)


@receiver(post_save, sender=InfoPageModel)
def pre_save_news_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(r.randint(1, 10000)) + "-" + str(r.randint(1, 10000)))

core/models/portfolio.py
from ckeditor.fields import RichTextField
from django.db import models
from core.models.home import upload_location


class PortfolioModel(models.Model):
    img = models.ImageField(upload_to=upload_location, blank=True, null=True)
    title = models.CharField(max_length=255)
    body = RichTextField()

    @property
    def imageURL(self):
        try:
            url = str(self.img.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Bizning loyihalarimiz'
        verbose_name_plural = 'Bizning loyihalarimiz'

core/models/services.py
from django.db import models
from core.models.home import upload_location


class ServicesModel(models.Model):
    img = models.ImageField(upload_to=upload_location, blank=True, null=True)
    title = models.TextField()

    @property
    def imageURL(self):
        try:
            url = str(self.img.url)
        except:
            url = ''

        return url

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Bizning xizmatlar'
        verbose_name_plural = 'Bizning xizmatlar'


class ProjectFormModel(models.Model):
    full_name = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=255, null=True)
    email = models.EmailField(null=True)
    message = models.TextField()

    def __str__(self):
        return str(self.full_name)

    class Meta:
        verbose_name = 'Qoldirilgan arizalar'
        verbose_name_plural = 'Qoldirilgan arizalar'

core/forms.py
from core.models.services import ProjectFormModel
from django import forms


class ProjectForm(forms.ModelForm):
    class Meta:
        model = ProjectFormModel
        fields = ['full_name', 'phone_number', 'email', 'message']

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, ListView

from core.forms import ProjectForm
from core.models.portfolio import *
from core.models.services import *
from core.models.home import *
from core.models.about import *


class VacanciesView(ListView):
    model = VacancyModel
    template_name = 'core_pages/vacancy.html'
    context_object_name = 'vacancies'


class ContactUsView(TemplateView):
    template_name = 'core_pages/contact-us.html'


class PortfolioDetailView(DetailView):
    model = PortfolioModel
    template_name = 'core_pages/portfolio-detail.html'


def portfolio_page(request):
    portfolios = PortfolioModel.objects.all()[:6]

    context = {
        'portfolios': portfolios,

    }
    return render(request, 'core_pages/portfolio.html', context)


def about_us_page(request):
    informations = AboutInfoModel.objects.all()
    certificates = CertificatesModel.objects.all()
    categories = PartnerCategoryModel.objects.all()
    partners = PartnersModel.objects.all()

    context = {
        'informations': informations,
        'certificates': certificates,
        'categories': categories,
        'partners': partners,
    }

    return render(request, 'core_pages/about.html', context)


def main_page(request):
    stats = StatsModel.objects.all()
    categories = PartnerCategoryModel.objects.all()
    partners = PartnersModel.objects.all()

    services1 = ServicesModel.objects.all()[0]
    services2 = ServicesModel.objects.all()[1]
    services3 = ServicesModel.objects.all()[2]
    services4 = ServicesModel.objects.all()[3]
    services5 = ServicesModel.objects.all()[4]
    services6 = ServicesModel.objects.all()[5]

    portfolios1 = PortfolioModel.objects.all()[0]
    portfolios2 = PortfolioModel.objects.all()[1]
    portfolios3 = PortfolioModel.objects.all()[2]
    portfolios4 = PortfolioModel.objects.all()[3]
    portfolios5 = PortfolioModel.objects.all()[4]
    portfolios6 = PortfolioModel.objects.all()[5]

    context = {
        'stats': stats,
        'categories': categories,
        'partners': partners,

        'services1': services1,
        'services2': services2,
        'services3': services3,
        'services4': services4,
        'services5': services5,
        'services6': services6,

        'portfolios1': portfolios1,
        'portfolios2': portfolios2,
        'portfolios3': portfolios3,
        'portfolios4': portfolios4,
        'portfolios5': portfolios5,
        'portfolios6': portfolios6,

    }

    if request.method == 'POST':
        form = ProjectForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            form = ProjectForm()
            return redirect('core:home')
        context['form'] = form

    return render(request, 'core_pages/home.html', context)

core/templates/core_pages/about.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <section class="about padding-150">
        <div class="about-inner mt-50">
            <div class="breadcrumb-with-title">
                <h1 class="section-big-text">{% trans "Biz haqimizda" %}</h1>
                <p> <a href="{% url 'core:home' %}">{% trans "Bosh sahifa" %} </a> / {% trans "Biz haqimizda" %}</p>
            </div>
            {% for info in informations %}
                <h1 class="inner-section-title">{{ info.title}}</h1>
                <p>{{ info.body|safe }}</p>
            {% endfor %}


            <h1 class="inner-section-title">{% trans 'Bizning mijozlar' %}</h1>

        <div id="tabs">
            <ul>
                {% for category in categories %}
                <li><a href="#tabs-{{ forloop.counter }}">{{ category.name}}</a></li>
                {% endfor %}

            </ul>
            {% for category in categories %}
                <div id="tabs-{{ forloop.counter }}" class="partners-grid">
                    {% for partner in partners %}
                        {% if partner.category == category %}
                            <img src="{{partner.imageURL}}" alt="">
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>


        <h1 class="inner-section-title">{% trans "Sertifikatlar va litsenziyalar" %}</h1>
        <div class="about-certificates">
            {% for certificate in certificates %}
                <img src="{{ certificate.imageURL }}" alt="">
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

core/templates/core_pages/contact-us.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <section class="contacts padding-150">
        <div class="contacts-inner mt-50">
            <div class="breadcrumb-with-title">
                <h1 class="section-big-text">{% trans "Biz bilan bog'lanish" %}</h1>
                <p> <a href="">{% trans "Bosh sahifa" %} </a> / {% trans "Bog'lanish" %}</p>
            </div>
            <div class="contacts-blocks">
                <div class="info">
                    <p>
                        <i class="fa fa-phone"></i>
                        <span>{% trans "Telefon raqami:" %}</span>
                    <p><a href="tel:">+99899 999-99-99</a></p>
                    </p>
                    <p>
                        <i class="fa fa-envelope"></i>
                        <span>{% trans "Elektron pochta:" %}</span>
                    <p>
                        <a href="mailto:itunisoft@gmail.com">itunisoft@gmail.com</a>
                    </p>
                    </p>
                    <p>
                        <i class="fa fa-map"></i>
                        <span>{% trans "Manzil:" %}</span>
                    <p>
                        {% trans "100015, 14 Afrosiyob ko'chasi" %}, <br> {% trans "Toshkent shahri, O'zbekiston" %}
                    </p>
                    </p>
                </div>
                <div class="map">
                    <div style="width: 100%">
                        <iframe width="100%" frameborder="0" scrolling="no" marginheight="0"
                            marginwidth="0"
                            src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=14%20Afrosiab%20Street,%20Tashkent%20100015+(IT%20Unisoft)&amp;t=&amp;z=17&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a
                                href="https://www.gps.ie/wearable-gps/">gps smartwatches</a>
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

core/templates/core_pages/portfolio-detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <section class="portfolios padding-150">
        <div class="portfolios-inner mt-50">
            <div class="breadcrumb-with-title">
                <h1 class="section-big-text">{{ object.title}}</h1>
                <p> <a href="{% url 'core:home' %}">{% trans "Bosh sahifa" %} </a> / <a href="{% url 'core:portfolio' %}"> {% trans "Loyihalarimiz" %} </a> / {{ object.title}}</p>
            </div>
            <div class="portfolios-banner">
                <img src="{{ object.imageURL}}" alt="">
            </div>
            <div class="portfolios-text">
                <p>
                    {{ object.body|safe }}
                </p>
                <a href="" class="button-style">{% trans 'Batafsil' %}</a>
            </div>
        </div>
    </section>
{% endblock %}

core/templates/core_pages/portfolio.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <section class="portfolios padding-150">
        <div class="portfolios-inner mt-50">
            <div class="breadcrumb-with-title">
                <h1 class="section-big-text">{% trans "Loyihalarimiz" %}</h1>
                <p> <a href="{% url 'core:home' %}">{% trans "Bosh sahifa" %} </a> / {% trans "Loyihalarimiz" %}</p>
            </div>
            <div class="portfolio-grid">
                <div class="grid-items about_animation invisible">

                    {% for portfolio in portfolios %}
                        <a href="{% url 'core:portfolio-detail' portfolio.id  %}">
                            <img src="{{ portfolio.imageURL}}" alt="">
                            <span>{{ portfolio.title}}</span>
                        </a>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>
{% endblock %}

core/templates/core_pages/vacancy.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <section class="vacancy padding-150">
        <div class="vacancy-inner mt-50">
            <div class="breadcrumb-with-title">
                <h1 class="section-big-text">{% trans "Vakansiyalar" %}</h1>
                <p> <a href="{% url 'core:home' %}">{% trans "Bosh sahifa" %} </a> / {% trans "Vakansiya" %}</p>
            </div>
            <div class="vacancy-list">
                {% for vacancy in vacancies %}
                <button class="accordion">{{ vacancy.title }}</button>
                <div class="panel">
                    <p>
                    {{ vacancy.body|safe }}

                    <a href="">itunisoft@gmail.com</a>
                    </p>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}