core/urls.py
from django.urls import path

from core.views import main_page, portfolio_page, about_us_page, PortfolioDetailView, ContactUsView, VacanciesView

app_name = "core"

urlpatterns = [
    path('', main_page, name='home'),
    path('about', about_us_page, name='about us'),
    path('portfolio', portfolio_page, name='portfolio'),
    path('portfolio/<int:pk>', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('contacts', ContactUsView.as_view(), name='contacts'),
    path('vacancies', VacanciesView.as_view(), name='vacancies'),

]

itunisoft_hybrid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = "IT UniSoft Admin"
admin.site.site_title = "IT UniSoft Admin Portal"
admin.site.index_title = "Welcome to IT UniSoft Admin official web-site!"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'main_app')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('main/', include('core.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/header.html
{% load static %}
{% load i18n %}
<nav class="nav padding-150">
    <a href="{% url 'core:home' %}" class="logo"><img src="{% static 'data/img/logo-dark.svg' %}" alt=""></a>
    <div class="nav-collapse" id="nav-collapse">
        <button class="close_menu">
            <i class="fa fa-times"></i>
        </button>
        <ul class="nav-list nav-list-center">
            <li><a href="{% url 'core:about us' %}">{% trans "Biz haqimizda" %}</a></li>
            <li><a href="{% url 'core:home' %}#services-section">{% trans "Xizmatlar" %}</a></li>
            <li><a href="{% url 'core:portfolio' %}">{% trans "Loyihalarimiz" %}</a></li>
            <li><a href="{% url 'core:home' %}#partners">{% trans "Mijozlar" %}</a></li>
            <li><a href="{% url 'core:contacts'%}">{% trans "Bog'lanish" %}</a></li>
            <li><a href="{% url 'core:vacancies' %}">{% trans "Vakansiya" %}</a></li>
        </ul>

        <ul class="nav-list nav-list-right">

            <li>
                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language" onchange="this.form.submit()" class="lang-select">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        {% for language in languages %}
                            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}

                    </select>
                </form>
            </li>
            <li class="nav-tel-number"><a href="tel:+998901330381">(90) 133-03-81</a></li>
        </ul>
    </div>
    <button class="open_menu">
        <i class="fa fa-bars"></i>
    </button>
</nav>